Testing

diff --git a/init b/init
--- a/init
+++ b/init
@@ -26,7 +26,7 @@ fi
 log "Looks like both docker and docker-compose are installed, everything looks good."
 
 log "Copying .env.example -> .env"
-cp src/.env.example src/.env
+cp ./src/.env.example ./src/.env
 if [ $? -ne 0 ]; then
     err "Error while copying .env"
 fi
@@ -40,34 +40,37 @@ if [ $? -ne 0 ]; then
 fi
 
 log "Installing dependencies"
-docker exec laravel composer install
+docker-compose run --rm composer install
 if [ $? -ne 0 ]; then
     err "Error while installing dependencies."
 fi
 
 log "Generating app key"
-docker exec laravel php artisan key:generate && \
-docker exec laravel php artisan cache:clear
+docker-compose run --rm artisan key:generate && \
+docker-compose run --rm artisan cache:clear
 if [ $? -ne 0 ]; then
     err "Error while generating app key."
 fi
 
-# log "Generating JWT key"
-# docker exec laravel php artisan jwt:secret && \
-# docker exec laravel php artisan cache:clear
-# if [ $? -ne 0 ]; then
-#     err "Error while generating JWT key."
-# fi
-
 log "Running database migrations"
-docker exec laravel php artisan migrate
+docker-compose run --rm artisan migrate
 if [ $? -ne 0 ]; then
     err "Error while running database migrations."
 fi
 
-log "Setting permissions for storage and bootstrap cache, this might ask you for your password"
-sudo chmod -R 777 src/storage src/bootstrap/cache
-if [ $? -ne 0 ]; then
-    err "Error while setting permissions."
-fi
+# log "Installing npm packages"
+# docker-compose run --rm npm install
+# if [ $? -ne 0 ]; then
+#     err "Error while installing npm packages."
+# fi
 
+# log "Compiling assets."
+# docker-compose run --rm npm run dev
+# if [ $? -ne 0 ]; then
+#     err "Error while compiling assets."
+# fi
+
+log "Copying the pre commit hook"
+cp pre-commit .git/hooks/pre-commit
+
+log "Finished."
